baseURL = "https://tofubakery.github.io/fcj-workshop-QuickBite-NguyenBaoDat/"
relativeURLs = false
canonifyURLs = false
defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = false
theme = "hugo-theme-learn"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = "QuickBite - FCAJ bilingual internship and AWS workshop report"
  author = "Nguyễn Bảo Đạt"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableInlineCopyToClipBoard = true

[Languages]
[Languages.vi]
title = "Báo cáo FCAJ - QuickBite"
weight = 1
label = "Tiếng Việt"
locale = "vi-VN"

[[Languages.vi.menu.shortcuts]]
name = "QuickBite GitHub"
identifier = "QuickBite GitHub"
url = "https://github.com/edrictrn/quickbite"
weight = 10

[[Languages.vi.menu.shortcuts]]
name = "AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "AWS Study Group - Facebook"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 21

[Languages.en]
title = "FCAJ Report - QuickBite"
weight = 2
label = "English"
locale = "en-US"

[[Languages.en.menu.shortcuts]]
name = "QuickBite GitHub"
identifier = "QuickBite GitHub"
url = "https://github.com/edrictrn/quickbite"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "AWS Study Group - Facebook"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 21

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
